#!/bin/ksh

if [ $# -ne 2 ] ;then
	echo "Usage: int -s [script-file]"
        exit 1
fi

umask 111
HOME=/bassapp/bass1
export HOME
. /bassapp/bass1/.profile

typeset param=$1
typeset script=$2

typeset intfile="${HOME}/tcl/int_main.tcl"

echo "#######################\n"
echo "$script\n"

tclsh $intfile -s $script -u 0 -v 0

echo "########################\n"
