######################################################################################################
alias pzr='sh $myroot/_src/ready/nohup.sh'
alias pzv='cat $myroot/_src/ready/a.out'
alias pzi='dpzd1;cat $myroot/_src/ready/a.sql'
alias inn='cd $myroot/indata/'
alias out='cd $myroot/outdata/'
alias pzrd='cd $myroot/_src/ready'
alias con22='db2 connect to acrm user '`whoami`
alias pzcon='sh ~/panzw/sh/db2connect'
alias desc='db2 describe table '
alias selall='sh $myroot/bin/db2_sql_shortcut_cmd_in_shell.sh'
alias nh='sh $myroot/_src/ready/nh'
######################################ftp to 284 , a fort #################
alias ftp284='ftp 10.244.28.4'
alias pzu='echo \$ pzudata | ftp 10.244.28.4'
alias pzd='echo \$ pzddata | ftp 10.244.28.4'
alias pzdsh='echo \$ pzdsh | ftp 10.244.28.4'
alias pzdsql='echo \$ pzdsql | ftp 10.244.28.4'
##################################### ftp to dm #########################
alias ftpdm='ftp 10.243.216.185'
alias dpzu='echo \$ pzudata | ftp 10.243.216.185'
alias dpzd='echo \$ pzddata | ftp 10.243.216.185'
alias dpzdsh='echo \$ pzdsh | ftp 10.243.216.185'
alias dpzdsql='echo \$ pzdsql | ftp 10.243.216.185'
alias dpzd1='echo \$ pzdacrmrunsql | ftp 10.243.216.185'
alias dpzaindout='echo \$ pzdaindout | ftp 10.243.216.185'
alias l211='echo \$ local_284_ftp_211| ftp 10.244.28.4'

##########################ftp shortcut defination######################
alias a2dup='sh $myroot/bin/a2dup.sh'
alias a24up='sh $myroot/bin/a24up.sh'
alias expln='sh $myroot/bin/expln.sh'
alias ftphere='cp ~/panzw/.ftp_tmp/* .;rm -r ~/panzw/.ftp_tmp/*'
alias pconf='cd ~/panzw/.wcwp/'
alias nhpwd='sh $shroot/nhpwd.sh'
alias sql='sh $shroot/onelinesql.sh'
alias spool='sh $shroot/spool.sh'
alias t4='sh $shroot/t4.sh'
alias req='cd $myroot/.req'
alias ldr='sh $shroot/ldr.sh'
alias fh='cp ~/panzw/.ftp_tmp/* .;rm -r ~/panzw/.ftp_tmp/*'
alias sedm='sh $shroot/sedm.sh'
alias l38='echo \$ local_38_ftp_211| ftp -i 10.244.28.38'
alias ta='sh $shroot/ta.sh'
alias sd='sh $shroot/sd.sh'
alias cr='sh $shroot/cr.sh'
