/*
函数功能：把用10进制表达IP地址转换成 AABBCCDD 格式表达的16进制串。
*/
--原函数
CREATE FUNCTION FN_CHANGE_DTOH(AS_IP VARCHAR(20)) 
RETURNS VARCHAR(20) DETERMINISTIC NO EXTERNAL ACTION 
LANGUAGE SQL
BEGIN ATOMIC DECLARE STRING VARCHAR(20); 
SET STRING =RIGHT(CHAR(HEX(INT(SUBSTR(AS_IP,1,POSSTR(AS_IP,'.')-1)))),2)
|| RIGHT(CHAR(HEX(INT(SUBSTR(SUBSTR(AS_IP,5),1,POSSTR(SUBSTR(AS_IP,5),'.')-1)))),2)
|| RIGHT(CHAR(HEX(INT(SUBSTR(SUBSTR(SUBSTR(AS_IP,5),5),1,POSSTR(SUBSTR(SUBSTR(AS_IP,5),5),'.')-1)))), 2)
|| RIGHT(CHAR(HEX(INT(SUBSTR(SUBSTR(SUBSTR(AS_IP,5),5),POSSTR(SUBSTR(SUBSTR(AS_IP,5),5),'.')+1)))),2); 
RETURN STRING; 
END



--优化后函数
CREATE FUNCTION FN_CHANGE_DTOH2(AS_IP VARCHAR(20)) 
RETURNS VARCHAR(20) 
DETERMINISTIC NO EXTERNAL ACTION 
LANGUAGE SQL
BEGIN 
ATOMIC 
DECLARE STRING VARCHAR(20); 
SET STRING =RIGHT(CHAR(HEX(INT(SUBSTR(AS_IP,1,POSSTR(AS_IP,'.')-1)))),2)
||RIGHT(CHAR(HEX(INT(SUBSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),1,POSSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),'.')-1)))),2)
||RIGHT(CHAR(HEX(INT(SUBSTR(substr(substr(AS_IP,POSSTR(AS_IP,'.')+1),POSSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),'.')+1),1,POSSTR(substr(substr(AS_IP,POSSTR(AS_IP,'.')+1),POSSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),'.')+1),'.')-1)))),2)
||RIGHT(CHAR(HEX(INT(substr(substr(substr(AS_IP,POSSTR(AS_IP,'.')+1),POSSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),'.')+1),POSSTR(substr(substr(AS_IP,POSSTR(AS_IP,'.')+1),POSSTR(substr(AS_IP,POSSTR(AS_IP,'.')+1),'.')+1),'.')+1)))),2); 
RETURN STRING; 
END
